name: Windows Qt Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Если есть подмодули

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'  # Укажите нужную версию Qt (можно 5.15.2, если проект использует Qt5)
        dir: 'C:\Qt'  # Путь установки (можно не менять)
        install-deps: true  # Установить зависимости (MinGW/MSVC)
        cached: true  # Кэширование для ускорения сборки
        setup-python: false  # Python не нужен (если не требуется)

    - name: Add Qt to PATH
      shell: cmd
      run: |
        call "C:\Qt\6.5.0\msvc2019_64\bin\qtenv2.bat"  # Для Qt6 + MSVC
        # Если используется MinGW:
        # call "C:\Qt\6.5.0\mingw_64\bin\qtenv2.bat"
        qmake --version

    - name: Build with qmake
      shell: cmd
      run: |
        qmake -recursive FreeSSM.pro  # Или другой .pro файл, если он называется иначе
        nmake release  # Для MSVC
        # Если MinGW: mingw32-make release

    - name: Collect binaries
      shell: cmd
      run: |
        mkdir artifacts
        copy release\*.exe artifacts\  # Или другой путь, куда собирается бинарник
        7z a artifacts.zip .\artifacts\*

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: FreeSSM-Windows
        path: artifacts.zip
