name: Windows Qt Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  QT_VERSION: "6.8.3"
  QT_ARCH: "win64_msvc2022_64"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Если есть подмодули

    - name: Setup Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ env.QT_VERSION }}
        target: "desktop"
        arch: ${{ env.QT_ARCH }}
        # use-official: true
        # email: ${{ secrets.QT_EMAIL }}
        # pw: ${{ secrets.QT_PW }}

    - name: Setup Qt environment
      shell: cmd
      run: |
        qmake --version

    - name: Build with qmake
      shell: cmd
      run: |
        qmake
        make release

    # - name: Collect binaries
    #   shell: cmd
    #   run: |
    #     mkdir artifacts
    #     copy release\*.exe artifacts\  # Или другой путь, куда собирается бинарник
    #     7z a artifacts.zip .\artifacts\*

    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: FreeSSM-Windows
    #     path: artifacts.zip
