name: Windows Qt Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Если есть подмодули

    - name: Setup Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        use-official: true
        email: ${{ secrets.QT_EMAIL }}
        pw: ${{ secrets.QT_PW }}

    - name: Build with qmake
      shell: cmd
      run: |
        qmake -recursive FreeSSM.pro  # Или другой .pro файл, если он называется иначе
        nmake release  # Для MSVC
        # Если MinGW: mingw32-make release

    - name: Collect binaries
      shell: cmd
      run: |
        mkdir artifacts
        copy release\*.exe artifacts\  # Или другой путь, куда собирается бинарник
        7z a artifacts.zip .\artifacts\*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FreeSSM-Windows
        path: artifacts.zip
